In [13]:
import tushare as tu
import pandas as pd
import talib as ta

In [4]:
stock_codes = pd.read_csv('stock.csv')
stock_codes = stock_codes['code']

0       872925
1       871981
2       871642
3       871553
4       871396
         ...
4817    600145
4818    600139
4819    600122
4820    600112
4821    600093
Name: code, Length: 4822, dtype: int64

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2

           date  open  close  high   low    volume    code
0    2019-06-26  3.33   3.32  3.35  3.29  123268.0  600122
1    2019-06-27  3.32   3.35  3.37  3.31  137690.0  600122
2    2019-06-28  3.32   3.21  3.35  3.17  210800.0  600122
3    2019-07-01  3.27   3.32  3.33  3.24  192815.0  600122
4    2019-07-02  3.33   3.37  3.43  3.32  212825.0  600122
..          ...   ...    ...   ...   ...       ...     ...
636  2022-02-11  1.82   1.82  1.83  1.77  172232.0  600122
637  2022-02-14  1.82   1.91  1.91  1.79  329610.0  600122
638  2022-02-15  1.88   1.81  1.91  1.81  255059.0  600122
639  2022-02-16  1.90   1.90  1.90  1.90   38594.0  600122
640  2022-02-17  2.00   2.00  2.00  2.00   21288.0  600122

[641 rows x 7 columns]

DatetimeIndex(['2019-06-26', '2019-06-27', '2019-06-28', '2019-07-01',
               '2019-07-02', '2019-07-03', '2019-07-04', '2019-07-05',
               '2019-07-08', '2019-07-09',
               ...
               '2022-01-28', '2022-02-07', '2022-02-08', '2022-02-09',
               '2022-02-10', '2022-02-11', '2022-02-14', '2022-02-15',
               '2022-02-16', '2022-02-17'],
              dtype='datetime64[ns]', name='date', length=641, freq=None)

In [44]:
def choose(df):
    stock_data = df
    stock_data['ma5'] = ta.EMA(stock_data['close'], timeperiod=5)
    stock_data['ma10'] = ta.EMA(stock_data['close'], timeperiod=10)
    stock_data['ma30'] = ta.EMA(stock_data['close'], timeperiod=30)
    stock_data['ma250'] = ta.EMA(stock_data['close'], timeperiod=250)
    hit = (stock_data['ma5'][-1] >= stock_data['ma10'][-1])  \
        and (stock_data['ma10'][-1] >= stock_data['ma30'][-1]) \
        and (stock_data['ma30'][-1] >= stock_data['ma250'][-1])
    return hit

In [ ]:
def get_data(code):
    df = tu.get_k_data(code=code)
    if not df.empty:
        df.index = pd.to_datetime(df['date'])
        return df[['open','close','high','low','volume']]
    return None

hit_codes =[]

for code in stock_codes[1000:1050]:
    df = get_data(str(code))
    if df is not None:
        if choose(df):
            hit_codes.append(code)

print ('all codes: %s'% hit_codes)

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
all codes: [603155, 603123, 603112, 603110, 603106, 603101, 603099, 603095, 603081, 603080]